points:
  key:
    padding: cy
  zones:
    matrix:
      anchor:
      rows:
        bottom:
          bind: [1,2,1,2]
        home:
          bind: [1,2,1,2]
        top:
          bind: [1,2,1,2]
      columns:
        outer:
          key.spread: cx
          key.splay: 6
          rows:
            bottom:
              net: /outer_bottom
            home:
              net: /outer_home
            top:
              net: /outer_top
        pinky:
          key.spread: cx
          rows:
            bottom:
              net: /pinky_bottom
            home:
              net: /pinky_home
            top:
              net: /pinky_top
        ring:
          key.spread: cx+0.5
          key.splay: -3
          key.stagger: 15
          rows:
            bottom:
              net: /ring_bottom
            home:
              net: /ring_home
            top:
              net: /ring_top
        middle:
          key.spread: cx+0.5
          key.splay: -3
          key.stagger: 5
          rows:
            bottom:
              net: /middle_bottom
            home:
              net: /middle_home
            top:
              net: /middle_top
        index:
          key.spread: cx
          key.stagger: -7
          rows:
            bottom:
              net: /index_bottom
            home:
              net: /index_home
            top:
              net: /index_top
        inner:
          key.spread: cx
          rows:
            bottom:
              net: /inner_bottom
            home:
              net: /inner_home
            top:
              net: /inner_top
    thumbfan:
      anchor:
        ref: matrix_inner_bottom
        shift: [-8, -26]
        rotate: -17
      rows:
        thumb:
          bind: [1,1,1,2]
      columns:
        near:
          key.spread: cx
          rows:
            thumb:
              net: /near_thumb
        home:
          key.splay: -3
          key.spread: cx+0.5
          key.stagger: -0.5
          rows:
            thumb:
              net: /home_thumb
        far:
          key.splay: -3
          key.spread: cx+0.5
          key.stagger: -0.5
          rows:
            thumb:
              net: /far_thumb
outlines:
  raw:
    - what: rectangle
      where: /^matrix_.*/
      operation: add
      size: [cx, cy]
      bound: true
    - what: rectangle
      where: /^thumbfan_.*/
      operation: add
      size: [cx, cy]
      bound: true
    - what: polygon
      operation: add
      points: 
        - ref: matrix_pinky_bottom
          shift: [0,-cy/2-1]
        - ref: thumbfan_far_thumb
        - ref: matrix_inner_bottom
          shift: [23, -30]
        - ref: matrix_inner_top
          shift: [23, 1+cy/2]
        - ref: matrix_index_top
          shift: [0, 1+cy/2]
        # - ref: matrix_inner_bottom
        #   shift: [cx/2,cy/2+1]
        - ref: matrix_index_bottom
        - ref: matrix_pinky_home
  cutout:
    - what: outline
      name: raw
      operation: add
      fillet: 3
    - what: outline
      name: raw
      operation: add
      fillet: 2
  keycap_outlines:
    - what: rectangle
      where: /^matrix_.*/
      operation: add
      size: [cx-0.5, cy-0.5]
      bound: false
    - what: rectangle
      where: /^thumbfan_.*/
      operation: add
      size: [cx-0.5, cy-0.5]
      bound: false
pcbs:
  bd1:
    outlines:
      bd:
        outline: cutout
    footprints:
    - where: true
      what: choc
      params:
        from: "{{net}}"
        to: GND
        hotswap: true
        reverse: true
        keycaps: true
    template: kicad8

